aroma_shop/config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'home#index'

    get '/login', to: 'users#login'
    post '/login', to: 'users#authenticate'
    get 'forgot_password', to: 'users#forgot_password'
    get '/register', to: 'users#new'
    post '/register', to: 'users#create'

    get '/profile', to: 'profile#profile'
    get '/profile/:id', to: 'profile#profile', as: 'user_profile'
    resource :profile, controller: 'profile', only: [:show, :edit, :update, :create, :destroy]

    get '/logout', to: 'users#logout'
    resources :users, only: [:show, :edit, :update]

    get '/store', to: 'products#index'
    resources :products, only: [:index, :show]
    get 'products/category/:category_id', to: 'products#category', as: 'category_products'
    get 'products/subcategory/:subcategory_id', to: 'products#subcategory', as: 'subcategory_products'

    resources :reviews, only: [:create]

    post '/products/favourites', to: 'favourites#create', as: 'favourites'
    delete '/products/favourites', to: 'favourites#destroy', as: 'remove_favourite'
    get '/favourites', to: 'favourites#index'

    get '/orders', to: 'orders#index'
    post '/orders/add_to_cart', to: 'orders#add_to_cart', as: 'add_to_cart'
    post 'update_quantity/:id', to: 'orders#update_quantity', as: 'update_quantity'
    delete '/orders/remove_from_cart/:id', to: 'orders#remove_from_cart', as: 'remove_from_cart'
    post '/checkout', to: 'orders#checkout', as: 'checkout'
  end
end

aroma_shop/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

aroma_shop/app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

aroma_shop/app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_many :subcategories
end

aroma_shop/app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

aroma_shop/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :products, through: :order_items

  # Статуси замовлень
  enum status: { pending: 'pending', completed: 'completed' }
end

aroma_shop/app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

aroma_shop/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :brand
  has_many :reviews
  has_many :favourites
  has_many :order_items
  has_many :orders, through: :order_items
end

aroma_shop/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

aroma_shop/app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
end

aroma_shop/app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :favourites
  has_many :reviews
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false, message: 'уже зайнятий'},
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }


  validates :username, presence: true, uniqueness: { message: 'Такий користувач вже існує'}
end

aroma_shop/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

aroma_shop/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def add_to_cart
    @order = current_order
    @order_item = @order.order_items.find_or_initialize_by(product_id: params[:product_id])
    @order_item.quantity ||= 1
    @order_item.quantity += params[:quantity].to_i
    if @order_item.save
      redirect_to product_path(params[:product_id]), notice: 'Item added to cart.'
    else
      redirect_to product_path(params[:product_id]), alert: 'Failed to add item to cart.'
    end
  end

  def index
    @order = current_order
    @order_items = @order.order_items
  end

  def remove_from_cart
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    if @order_item.destroy
      redirect_to orders_path, notice: 'Item removed from cart.'
    else
      redirect_to orders_path, alert: 'Failed to remove item from cart.'
    end
  end

  def update_quantity
    @order_item = current_order.order_items.find(params[:id])
    if @order_item.update(quantity: params[:quantity])
      redirect_to orders_path, notice: 'Quantity updated.'
    else
      redirect_to orders_path, alert: 'Failed to update quantity.'
    end
  end

  def checkout
    @order = current_order

    if params[:commit] == t('Оформити')
      @order.update(status: 'completed', user_id: current_user.id, updated_at: Time.current)
      session[:order_id] = nil
      redirect_to root_path, notice: 'Order placed successfully.'
    else
      @first_name = params[:first_name]
      @last_name = params[:last_name]
      @city = params[:city]
      @address = params[:address]
      render :checkout_form
    end
  end

  private

  def current_order
    if session[:order_id]
      begin
        Order.find(session[:order_id])
      rescue ActiveRecord::RecordNotFound
        session[:order_id] = nil
        create_new_order
      end
    else
      create_new_order
    end
  end

  def create_new_order
    order = Order.create(user: current_user, status: 'pending')
    session[:order_id] = order.id
    order
  end
end

aroma_shop/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories = Category.all
    if params[:category_id]
      @products = Product.where(category_id: params[:category_id])
    elsif params[:subcategory_id]
      @products = Product.where(subcategory_id: params[:subcategory_id])
    else
      @products = Product.all
    end
  end

  def category
    @categories = Category.all
    @subcategories = Subcategory.where(category_id: params[:category_id])
    @products = Product.where(category_id: params[:category_id])
    render :index
  end

  def subcategory
    @categories = Category.all
    subcategory = Subcategory.find(params[:subcategory_id])
    @subcategories = Subcategory.where(category_id: subcategory.category_id)
    @products = Product.where(subcategory_id: params[:subcategory_id])
    render :index
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews
  end
end

aroma_shop/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  helper_method :current_user

  def login
  end

  def forgot_password
  end

  def authenticate
    user = User.find_by('email = ? OR username = ?', params[:login], params[:login])

    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path, alert: 'Невірний логін або пароль'
    end
  end

  def new
    @user = User.new
    render 'register'
  end

  def create
    @user = User.new(user_params.merge(admin: false))

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Ви успішно зареєструвались'
    else
      render :register
    end
  end

  def profile
    @user = current_user
    render 'profile'
  end

  def edit
    @user = current_user
  end

  def update
    if current_user.update(user_params)
      redirect_to edit_user_path(current_user), notice: 'Profile updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: 'User was successfully deleted.'
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :first_name, :last_name, :address, :phone_number)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def authorize_user
    redirect_to root_path, alert: 'Not authorized' unless current_user.admin? || current_user == @user
  end

end

aroma_shop/app/helpers/application_helper.rb
module ApplicationHelper
end

aroma_shop/app/helpers/checkout_helper.rb
module CheckoutHelper
end

aroma_shop/app/helpers/favourites_helper.rb
module FavouritesHelper
end

aroma_shop/app/helpers/home_helper.rb
module HomeHelper
end

aroma_shop/app/helpers/orders_helper.rb
module OrdersHelper
end

aroma_shop/app/helpers/product_helper.rb
module ProductHelper
end

aroma_shop/app/helpers/profile_helper.rb
module ProfileHelper
end

aroma_shop/app/helpers/reviews_helper.rb
module ReviewsHelper
end

aroma_shop/app/helpers/users_helper.rb
module UsersHelper
end

aroma_shop/app/views/products/index.html.erb
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= t('Магазин') %></title>
    <%= stylesheet_link_tag 'store.css' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap">
</head>
<body>
    <header>
        <div class="container">
            <div class="header-left">
                <h1>ITAroma</h1>
                <p><%= t('магазин ароматичних продуктів') %></p>
            </div>
            <nav>
                <ul>
                    <li><a href="/"><%= t('Головна') %></a></li>
                    <li><a href="/products"><%= t('Магазин') %></a></li>
                    <li><a href="#"><%= t('Про нас') %></a></li>
                    <li><a href="<%= session[:user_id] ? '/favourites' : login_path %>"><i class="material-icons">favorite</i></a></li>
                    <% if session[:user_id] %>
                        <li><a href="<%= profile_path %>"><i class="material-icons">person</i></a></li>
                    <% else %>
                        <li><a href="<%= login_path %>"><%= t('Увійти') %></a></li>
                    <% end %>
                    <li>
                        <a href="<%= session[:user_id] ? orders_path : login_path %>">
                            <i class="material-icons">shopping_cart</i>
                            <% if session[:user_id] %>
                            <% pending_order = Order.find_by(user_id: session[:user_id], status: 'pending') %>
                            <% if pending_order && pending_order.order_items.count > 0 %>
                                <%= pending_order.order_items.count %>
                            <% end %>
                            <% end %>
                        </a>
                    </li>
                    <li> 
                        <%= link_to image_tag(asset_path('ukraine.png')), url_for(locale: 'uk') %>
                        <%= link_to image_tag(asset_path('united-kingdom.png')), url_for(locale: 'en') %>
                    </li>
                </ul>
            </nav>
            
        </div>
    </header>

    <main>
        <section class="hero">
            <div class="hero-text">
                <h2><%= t('Магазин') %></h2>
                <style>
                    .hero {
                        position: relative;
                        height: 300px;
                        display: flex;
                        justify-content: center;
                        align-items: center;
                        margin-bottom: 50px;
                    }

                    .hero::before {
                        content: "";
                        position: absolute;
                        top: 0;
                        right: 0;
                        bottom: 0;
                        left: 0;
                        background-image: url(<%= asset_path 'main.jpg' %>);
                        background-repeat: no-repeat;
                        background-size: cover;
                        filter: blur(2px); 
                        z-index: -1;
                    }
                </style>
            </div>
        </section>

        <div class="category-selection">
            <%= link_to t('Всі'), products_path, class: 'category-button' %>
            <% @categories.each do |category| %>
                <div class="dropdown">
                    <%= link_to t(category.category_name), products_path(category_id: category.id), class: 'category-button dropdown-toggle' %>
                    <% if category.subcategories.present? %>
                        <div class="dropdown-menu">
                            <% category.subcategories.each do |subcategory| %>
                                <%= link_to t(subcategory.subcategory_name), products_path(subcategory_id: subcategory.id), class: 'dropdown-item' %>
                            <% end %>
                        </div>
                    <% end %>
                </div>
            <% end %>
        </div>

        <div class="product-grid">
            <% @products.each_slice(3) do |product_slice| %>
                <div class="product-row">
                    <% product_slice.each do |product| %>
                        <div class="product-item">
                            <a href="<%= product_path(product) %>" class="product-link">
                                <img src="<%= product.image_url %>" alt="<%= product.product_name %>">
                                <h3><%= t(product.product_name) %></h3>
                            </a>
                            <p class="category"><%= t(product.category.category_name) %></p>
                            <div class="stars">
                                <% average_rating = Review.where(product_id: product.id).average(:rating_value).to_f %>
                                <% for i in 1..5 %>
                                    <% if i <= average_rating %>
                                        <i class="fas fa-star"></i>
                                    <% elsif i - 0.5 <= average_rating %>
                                        <i class="fas fa-star-half-alt"></i>
                                    <% else %>
                                        <i class="far fa-star"></i>
                                    <% end %>
                                <% end %>
                                <span>(<%= Review.where(product_id: product.id).count %> <%= t('відгуків') %>)</span>
                            </div>
                            <div class="price"><%= product.price %> ₴</div>
                            <div class="buy-now">
                                <a href="<%= product_path(product) %>"><%= t('Купити') %></a>
                            </div>
                        </div>
                    <% end %>
                </div>
            <% end %>
        </div>
    </main>

    <footer>
        <div class="container footer-container">
        <div class="footer-left">
            <h1>ITAroma</h1>
            <p><%= t('магазин ароматичних продуктів') %></p>
        </div>
        <nav class="footer-nav">
            <ul>
            <li><a href="<%= root_path %>"><%= t('Головна') %></a></li>
            <li><a href="<%= products_path %>"><%= t('Магазин') %></a></li>
            <li><a href="#"><%= t('Про нас') %></a></li>
            </ul>
        </nav>
        <div class="social-media">
            <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
            <a href="https://www.twitter.com"><i class="fab fa-twitter"></i></a>
            <a href="https://www.facebook.com"><i class="fab fa-facebook-f"></i></a>
        </div>
        <div class="payment-methods">
            <i class="fab fa-cc-visa"></i> Visa
            <br>
            <i class="fab fa-cc-mastercard"></i> Mastercard
        </div>
        </div>
    </footer>
</body>
</html>

aroma_shop/app/views/products/show.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= @product.product_name %> - ITAroma</title>
    <%= stylesheet_link_tag 'show.css' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <div class="container">
            <div class="header-left">
                <h1>ITAroma</h1>
                <p><%= t('магазин ароматичних продуктів') %></p>
            </div>
            <nav>
                <ul>
                    <li><a href="/"><%= t('Головна') %></a></li>
                    <li><a href="/products"><%= t('Магазин') %></a></li>
                    <li><a href="#"><%= t('Про нас') %></a></li>
                    <li><a href="<%= session[:user_id] ? '/favourites' : login_path %>"><i class="material-icons">favorite</i></a></li>
                    <% if session[:user_id] %>
                        <li><a href="<%= profile_path %>"><i class="material-icons">person</i></a></li>
                    <% else %>
                        <li><a href="<%= login_path %>"><%= t('Увійти') %></a></li>
                    <% end %>
                    <li>
                        <a href="<%= session[:user_id] ? orders_path : login_path %>">
                            <i class="material-icons">shopping_cart</i>
                            <% if session[:user_id] %>
                            <% pending_order = Order.find_by(user_id: session[:user_id], status: 'pending') %>
                            <% if pending_order && pending_order.order_items.count > 0 %>
                                <%= pending_order.order_items.count %>
                            <% end %>
                            <% end %>
                        </a>
                    </li>
                    <li> 
                        <%= link_to image_tag(asset_path('ukraine.png')), url_for(locale: 'uk') %>
                        <%= link_to image_tag(asset_path('united-kingdom.png')), url_for(locale: 'en') %>
                    </li>
                </ul>
            </nav>
            
        </div>
    </header>
    <main>
    <section class="hero">
        <div class="hero-text">
            <style>
                .hero {
                    position: relative;
                    height: 300px;
                    display: flex;
                    justify-content: center;
                    align-items: center;
                    margin-bottom: 50px;
                }

                .hero::before {
                    content: "";
                    position: absolute;
                    top: 0;
                    right: 0;
                    bottom: 0;
                    left: 0;
                    background-image: url(<%= asset_path 'main.jpg' %>);
                    background-repeat: no-repeat;
                    background-size: cover;
                    filter: blur(2px); 
                    z-index: -1;
                }
            </style>
        </div>
    </section>

        <div class="product-details">
            <div class="product-info">
                <div class="product-name-category">
                    <h2><%= @product.product_name %></h2>
                    <p class="category"><%= @product.category.category_name %></p>
                    <div class="stars">
                        <% average_rating = Review.where(product_id: @product.id).average(:rating_value).to_f %>
                        <% for i in 1..5 %>
                            <% if i <= average_rating %>
                                <i class="fas fa-star"></i>
                            <% elsif i - 0.5 <= average_rating %>
                                <i class="fas fa-star-half-alt"></i>
                            <% else %>
                                <i class="far fa-star"></i>
                            <% end %>
                        <% end %>
                        <span>(<%= Review.where(product_id: @product.id).count %> <%= t('відгуків') %>)</span>
                    </div>
                </div>
                <div class="product-image">
                    <img src="<%= @product.image_url %>" alt="<%= @product.product_name %>">
                </div>
                <div class="product-buy">
                    <div class="price"><%= @product.price %> ₴</div>
                    <div class="buy-now">
                        <%= button_to t('Купити'), add_to_cart_path(product_id: @product.id), method: :post, class: "buy" %>
                    </div>
                    <div class="favourites">
                        <div class="articale">
                            <p><%= @product.quantity > 0 ? t('Є в наявності') : t('Немає в наявності') %></p>
                            <p><%= t('Код товару') %> <%= @product.id %></p>
                        </div>
                        <div class="favourites">
                        <% if session[:user_id] %>
                            <% favourite = Favourite.find_by(user_id: session[:user_id], product_id: @product.id) %>
                            <% if favourite %>
                                <%= button_to favourites_path(product_id: @product.id), method: :delete, class: 'favourite-button' do %>
                                <i class="fas fa-heart"></i>
                                <% end %>
                            <% else %>
                                <%= button_to favourites_path(product_id: @product.id), method: :post, class: 'favourite-button' do %>
                                <i class="far fa-heart"></i>
                                <% end %>
                            <% end %>
                            <% else %>
                            <%= link_to login_path do %>
                                <i class="far fa-heart"></i>
                            <% end %>
                        <% end %>
                    </div>
                    </div>
                </div>
            </div>

            <div class="product-description">
                <h3><%= t('Опис') %></h3> <br>
                <p><%= @product.description %></p>
            </div>
            <!-- Кнопка відгуку -->
            <% if session[:user_id] %>
                <button type="button" class="review-button" data-toggle="modal" data-target="#reviewModal"><%= t('Додати відгук') %></button>

                <div class="modal fade" id="reviewModal" tabindex="-1" role="dialog" aria-labelledby="reviewModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="reviewModalLabel"><%= t('Новий відгук') %></h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <%= form_for Review.new, url: {controller: "reviews", action: "create"}, html: {id: 'review-form'} do |f| %>
                                <div class="modal-body">
                                    <div class="form-group">
                                        
                                        <div class="rating-stars">
                                            <% 5.times do |i| %>
                                                <i class="fas fa-star" data-value="<%= i + 1 %>"></i>
                                            <% end %>
                                        </div>
                                        <%= f.hidden_field :rating_value, id: 'rating_value', class: 'form-control' %>
                                    </div>
                                    <div class="form-group">
                                        
                                        <%= f.text_area :review_text, class: 'form-control', rows: 5, placeholder: t("Додати коментар...") %>
                                    </div>
                                    <%= f.hidden_field :product_id, value: @product.id %>
                                    <%= f.hidden_field :user_id, value: session[:user_id] %>
                                </div>
                                <div class="modal-footer">
                                    <%= f.submit t("Додати відгук"), class: 'btn btn-primary' %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            <% else %>
                <%= link_to t('Додати відгук'), login_path, class: 'review-button' %>
            <% end %>

            <!-- Список відгуків -->
            <div class="product-reviews">
                <h3><%= t('Відгуки') %></h3>
                <% @reviews.each do |review| %>
                    <div class="review">
                        <h4><%= review.user.first_name %> <span><%=  review.created_at.strftime("%d/%m/%Y %H:%M:%S") %></span></h4>
                        <div class="stars">
                            <% for i in 1..5 %>
                                <% if i <= review.rating_value %>
                                    <i class="fas fa-star"></i>
                                <% else %>
                                    <i class="far fa-star"></i>
                                <% end %>
                            <% end %>
                        </div>
                        <p><%= review.review_text %></p>
                    </div>
                <% end %>
            </div>
        </div>
    </main>

    <footer>
        <div class="container footer-container">
        <div class="footer-left">
            <h1>ITAroma</h1>
            <p><%= t('магазин ароматичних продуктів') %></p>
        </div>
        <nav class="footer-nav">
            <ul>
            <li><a href="<%= root_path %>"><%= t('Головна') %></a></li>
            <li><a href="<%= products_path %>"><%= t('Магазин') %></a></li>
            <li><a href="#"><%= t('Про нас') %></a></li>
            </ul>
        </nav>
        <div class="social-media">
            <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
            <a href="https://www.twitter.com"><i class="fab fa-twitter"></i></a>
            <a href="https://www.facebook.com"><i class="fab fa-facebook-f"></i></a>
        </div>
        <div class="payment-methods">
            <i class="fab fa-cc-visa"></i> Visa
            <br>
            <i class="fab fa-cc-mastercard"></i> Mastercard
        </div>
        </div>
    </footer>


    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const stars = document.querySelectorAll('.rating-stars i');
            const ratingValue = document.getElementById('rating_value');
            stars.forEach(star => {
                star.addEventListener('click', function() {
                    const value = this.getAttribute('data-value');
                    ratingValue.value = value;
                    stars.forEach(s => {
                        if (s.getAttribute('data-value') <= value) {
                            s.classList.add('rated');
                        } else {
                            s.classList.remove('rated');
                        }
                    });
                });
            });

            document.getElementById('review-form').addEventListener('submit', function(event) {
                if (ratingValue.value === '') {
                    alert('<%= t('Будь ласка, оберіть рейтинг.') %>');
                    event.preventDefault();
                }
            });
        });
    </script>

 
</body>
</html>