aroma_shop/config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'home#index'

    get '/login', to: 'users#login'
    post '/login', to: 'users#authenticate'
    get 'forgot_password', to: 'users#forgot_password'
    get '/register', to: 'users#new'
    post '/register', to: 'users#create'

    get '/profile', to: 'profile#profile'
    get '/profile/:id', to: 'profile#profile', as: 'user_profile'
    resource :profile, controller: 'profile', only: [:show, :edit, :update, :create, :destroy]

    get '/logout', to: 'users#logout'
    resources :users, only: [:show, :edit, :update]

    get '/store', to: 'products#index'
    resources :products, only: [:index, :show]
    get 'products/category/:category_id', to: 'products#category', as: 'category_products'
    get 'products/subcategory/:subcategory_id', to: 'products#subcategory', as: 'subcategory_products'

    resources :reviews, only: [:create]

    post '/products/favourites', to: 'favourites#create', as: 'favourites'
    delete '/products/favourites', to: 'favourites#destroy', as: 'remove_favourite'
    get '/favourites', to: 'favourites#index'

    get '/orders', to: 'orders#index'
    post '/orders/add_to_cart', to: 'orders#add_to_cart', as: 'add_to_cart'
    post 'update_quantity/:id', to: 'orders#update_quantity', as: 'update_quantity'
    delete '/orders/remove_from_cart/:id', to: 'orders#remove_from_cart', as: 'remove_from_cart'
    post '/checkout', to: 'orders#checkout', as: 'checkout'
  end
end

aroma_shop/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

aroma_shop/app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

aroma_shop/app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_many :subcategories
end

aroma_shop/app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

aroma_shop/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :products, through: :order_items

  # Статуси замовлень
  enum status: { pending: 'pending', completed: 'completed' }
end

aroma_shop/app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

aroma_shop/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :brand
  has_many :reviews
  has_many :favourites
  has_many :order_items
  has_many :orders, through: :order_items
end

aroma_shop/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

aroma_shop/app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
end

aroma_shop/app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :favourites
  has_many :reviews
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false, message: 'уже зайнятий'},
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }


  validates :username, presence: true, uniqueness: { message: 'Такий користувач вже існує'}
end

aroma_shop/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

aroma_shop/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def add_to_cart
    @order = current_order
    @order_item = @order.order_items.find_or_initialize_by(product_id: params[:product_id])
    @order_item.quantity ||= 1
    @order_item.quantity += params[:quantity].to_i
    if @order_item.save
      redirect_to product_path(params[:product_id]), notice: 'Item added to cart.'
    else
      redirect_to product_path(params[:product_id]), alert: 'Failed to add item to cart.'
    end
  end

  def index
    @order = current_order
    @order_items = @order.order_items
  end

  def remove_from_cart
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    if @order_item.destroy
      redirect_to orders_path, notice: 'Item removed from cart.'
    else
      redirect_to orders_path, alert: 'Failed to remove item from cart.'
    end
  end

  def update_quantity
    @order_item = current_order.order_items.find(params[:id])
    if @order_item.update(quantity: params[:quantity])
      redirect_to orders_path, notice: 'Quantity updated.'
    else
      redirect_to orders_path, alert: 'Failed to update quantity.'
    end
  end

  def checkout
    @order = current_order

    if params[:commit] == t('Оформити')
      @order.update(status: 'completed', user_id: current_user.id, updated_at: Time.current)
      session[:order_id] = nil
      redirect_to root_path, notice: 'Order placed successfully.'
    else
      @first_name = params[:first_name]
      @last_name = params[:last_name]
      @city = params[:city]
      @address = params[:address]
      render :checkout_form
    end
  end

  private

  def current_order
    if session[:order_id]
      begin
        Order.find(session[:order_id])
      rescue ActiveRecord::RecordNotFound
        session[:order_id] = nil
        create_new_order
      end
    else
      create_new_order
    end
  end

  def create_new_order
    order = Order.create(user: current_user, status: 'pending')
    session[:order_id] = order.id
    order
  end
end

aroma_shop/app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def create
    @user = User.new(user_params)
    @user.admin = false
    redirect_to profile_path, notice: 'Profile was successfully updated.'
    if @user.save
    else
    redirect_to profile_path, notice: 'Profile was successfully updated.'
    end
  end

  def update
    if current_user.update(user_params)
      redirect_to profile_path, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  def profile
    @users = User.all
    @user = User.find(session[:user_id])
    @orders = @user.orders
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    admin = User.find_by(admin: true)
    redirect_to user_profiles_path(admin.id), notice: 'Користувач був успішно видалений.'
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone_number, :password, :address, :username)
  end
end

aroma_shop/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  helper_method :current_user

  def login
  end

  def forgot_password
  end

  def authenticate
    user = User.find_by('email = ? OR username = ?', params[:login], params[:login])

    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path, alert: 'Невірний логін або пароль'
    end
  end

  def new
    @user = User.new
    render 'register'
  end

  def create
    @user = User.new(user_params.merge(admin: false))

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Ви успішно зареєструвались'
    else
      render :register
    end
  end

  def profile
    @user = current_user
    render 'profile'
  end

  def edit
    @user = current_user
  end

  def update
    if current_user.update(user_params)
      redirect_to edit_user_path(current_user), notice: 'Profile updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: 'User was successfully deleted.'
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :first_name, :last_name, :address, :phone_number)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def authorize_user
    redirect_to root_path, alert: 'Not authorized' unless current_user.admin? || current_user == @user
  end

end

aroma_shop/app/helpers/application_helper.rb
module ApplicationHelper
end

aroma_shop/app/helpers/checkout_helper.rb
module CheckoutHelper
end

aroma_shop/app/helpers/favourites_helper.rb
module FavouritesHelper
end

aroma_shop/app/helpers/home_helper.rb
module HomeHelper
end

aroma_shop/app/helpers/orders_helper.rb
module OrdersHelper
end

aroma_shop/app/helpers/product_helper.rb
module ProductHelper
end

aroma_shop/app/helpers/profile_helper.rb
module ProfileHelper
end

aroma_shop/app/helpers/reviews_helper.rb
module ReviewsHelper
end

aroma_shop/app/helpers/users_helper.rb
module UsersHelper
end

aroma_shop/app/views/orders/index.html.erb
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Магазин</title>
    <%= stylesheet_link_tag 'order.css' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <div class="container">
            <div class="header-left">
                <h1>ITAroma</h1>
                <p><%= t('магазин ароматичних продуктів') %></p>
            </div>
            <nav>
                <ul>
                    <li><a href="/"><%= t('Головна') %></a></li>
                    <li><a href="/products"><%= t('Магазин') %></a></li>
                    <li><a href="#"><%= t('Про нас') %></a></li>
                    <li><a href="<%= session[:user_id] ? '/favourites' : login_path %>"><i class="material-icons">favorite</i></a></li>
                    <% if session[:user_id] %>
                        <li><a href="<%= profile_path %>"><i class="material-icons">person</i></a></li>
                    <% else %>
                        <li><a href="<%= login_path %>"><%= t('Увійти') %></a></li>
                    <% end %>
                    <li>
                        <a href="<%= session[:user_id] ? orders_path : login_path %>">
                            <i class="material-icons">shopping_cart</i>
                            <% if session[:user_id] %>
                            <% pending_order = Order.find_by(user_id: session[:user_id], status: 'pending') %>
                            <% if pending_order && pending_order.order_items.count > 0 %>
                                <%= pending_order.order_items.count %>
                            <% end %>
                            <% end %>
                        </a>
                    </li>
                    <li> 
                        <%= link_to image_tag(asset_path('ukraine.png')), url_for(locale: 'uk') %>
                        <%= link_to image_tag(asset_path('united-kingdom.png')), url_for(locale: 'en') %>
                    </li>
                </ul>
            </nav>
        </div>
    </header>

    <main>
        <section class="hero">
            <div class="hero-text">
                <h2><%= t('Ваші замовлення') %></h2>
                <style>
                    .hero {
                        position: relative;
                        height: 300px;
                        display: flex;
                        justify-content: center;
                        align-items: center;
                        margin-bottom: 50px;
                    }

                    .hero::before {
                        content: "";
                        position: absolute;
                        top: 0;
                        right: 0;
                        bottom: 0;
                        left: 0;
                        background-image: url(<%= asset_path 'main.jpg' %>);
                        background-repeat: no-repeat;
                        background-size: cover;
                        filter: blur(2px); 
                        z-index: -1;
                    }
                </style>
            </div>
        </section>
        <div class="list-items">
            <h2><%= t('Ваш кошик') %></h2>
            <% if @order_items.any? %>
            <table>
                <thead>
                <tr>
                    <th><%= t('Товар') %></th>
                    <th class="name-left"><%= t('Назва') %></th>
                    <th><%= t('Кількість') %></th>
                    <th><%= t('Ціна') %></th>
                    <th><%= t('Дія') %></th>
                </tr>
                </thead>
                <tbody>
                <% @order_items.each do |item| %>
                <tr>
                    <td><%= image_tag item.product.image_url, class: 'product-image' %></td>
                    <td class='product_name'><%= item.product.product_name %></td>
                    <td>
                    <%= button_to '+', update_quantity_path(item.id, quantity: item.quantity + 1), method: :post, class: 'quantity-button' %>
                    <span class="quantity"><%= item.quantity %></span>
                    <%= button_to '-', update_quantity_path(item.id, quantity: item.quantity - 1), method: :post, class: 'quantity-button' if item.quantity > 1 %>
                    </td>
                    <td><%= item.product.price * item.quantity %> ₴</td>
                    <td><%= button_to t('Видалити'), remove_from_cart_path(item.id), method: :delete, class: 'delete-button' %></td>
                </tr>
                <% end %>
                </tbody>
            </table>
            <div class="checkout">
                <h3><%= t('Загальна вартість') %> <%= @order_items.sum { |item| item.product.price * item.quantity } %> ₴</h3>
                <button type="button" class="checkout-button" data-toggle="modal" data-target="#checkoutModal"><%= t('Оформити замовлення') %></button>
            </div>

            <div class="modal fade" id="checkoutModal" tabindex="-1" role="dialog" aria-labelledby="checkoutModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="checkoutModalLabel"><%= t('Оформлення замовлення') %></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                    <%= form_with url: checkout_path, method: :post, local: true do |f| %>
                        <div class="form-group">
                        <%= f.label :first_name, t('Ім\'я') %>
                        <%= f.text_field :first_name, value: current_user.first_name, class: 'form-control' %>
                        </div>
                        <div class="form-group">
                        <%= f.label :last_name, t('Прізвище') %>
                        <%= f.text_field :last_name, value: current_user.last_name, class: 'form-control' %>
                        </div>
                        <div class="form-group">
                        <%= f.label :city, t('Місто') %>
                        <%= f.text_field :city, class: 'form-control' %>
                        </div>
                        <div class="form-group">
                        <%= f.label :address, t('Адреса') %>
                        <%= f.text_field :address, class: 'form-control' %>
                        </div>
                        <div class="modal-footer">
                        <%= f.submit t('Оформити'), class: 'btn btn-primary' %>
                        </div>
                    <% end %>
                    </div>
                </div>
                </div>
            </div>
            <% else %>
                <p><%= t('Ваш кошик порожній') %></p>
            <% end %>
        </div>
    </main>

    <footer>
        <div class="container footer-container">
        <div class="footer-left">
            <h1>ITAroma</h1>
            <p><%= t('магазин ароматичних продуктів') %></p>
        </div>
        <nav class="footer-nav">
            <ul>
            <li><a href="<%= root_path %>"><%= t('Головна') %></a></li>
            <li><a href="<%= products_path %>"><%= t('Магазин') %></a></li>
            <li><a href="#"><%= t('Про нас') %></a></li>
            </ul>
        </nav>
        <div class="social-media">
            <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
            <a href="https://www.twitter.com"><i class="fab fa-twitter"></i></a>
            <a href="https://www.facebook.com"><i class="fab fa-facebook-f"></i></a>
        </div>
        <div class="payment-methods">
            <i class="fab fa-cc-visa"></i> Visa
            <br>
            <i class="fab fa-cc-mastercard"></i> Mastercard
        </div>
        </div>
    </footer>
</body>
</html>

aroma_shop/app/views/users/login.html.erb
<html>
    <head>
        <title><%= t('Авторизація') %></title>
        <%= stylesheet_link_tag 'login' %>
    </head>
    <body>
        <div class="main-div">
            <%= form_with(url: login_path, method: :post, local: true, id: "login-form") do %>
                <h1 id="login-title"><%= t('Авторизація') %></h1>
                <% if flash[:alert] %>
                <div class="alert-danger">
                    <%= flash[:alert] %>
                </div>
                <% end %>
                <div class="form-group">
                    <%= label_tag(:login, t("Email або ім'я користувача"), id: "login-label") %>
                    <%= text_field_tag(:login, nil, id: "login-field") %>
                </div>
                <div class="form-group">
                    <%= label_tag(:password, t("Пароль"), id: "password-label") %>
                    <%= password_field_tag(:password, nil, id: "password-field") %>
                </div>
                <div class="form-group">
                    <%= submit_tag(t("Увійти"), id: "login-button") %>
                </div>
                <div class="form-group">
                    <%= link_to t('Ще немає аккаунта?'), register_path, class: 'login-button' %>
                    <%= link_to t('Забув пароль?'), forgot_password_path, class: 'login-button' %>
                </div>
            <% end %>
        </div>
    </body>
</html>

aroma_shop/app/views/users/register.html.erb
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= t('Реєстрація') %></title>
    <%= stylesheet_link_tag 'register' %>
</head>
<body>
    <div class="main-div">
        <% if @user.errors.any? %>
            <div class="alert-danger">
                <% @user.errors.full_messages.each do |message| %>
                    <div> <%= message %> </div>
                <% end %>
            </div>
        <% end %>

        <%= form_with(model: @user, url: register_path, id: "register-form") do |f| %>
            <h1 id="register-title"><%= t('Реєстрація') %></h1>
            <div class="form-group">
                <%= f.label :username, t('Логін користувача'), id: "username-label" %>
                <%= f.text_field :username, id: "username-field", value: @user.errors[:username].any? ? @user.errors[:username].first : @user.username %>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <%= f.label :first_name, t("Ім'я"), id: "first-name-label" %>
                    <%= f.text_field :first_name, id: "first-name-field" %>
                </div>
                <div class="form-group col-md-6">
                    <%= f.label :last_name, t('Прізвище'), id: "last-name-label" %>
                    <%= f.text_field :last_name, id: "last-name-field" %>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <%= f.label :address, t('Адреса'), id: "address-label" %>
                    <%= f.text_field :address, id: "address-field" %>
                </div>
                <div class="form-group col-md-6">
                    <%= f.label :phone_number, t('Номер телефону'), id: "phone-number-label" %>
                    <%= f.telephone_field :phone_number, id: "phone-number-field" %>
                </div>
            </div>
            <div class="form-group">
                <%= f.label :email, t('Електронна пошта'), id: "email-label" %>
                <%= f.email_field :email, id: "email-field" %>
            </div>
            <div class="form-group">
                <%= f.label :password, t('Пароль'), id: "password-label" %>
                <%= f.password_field :password, id: "password-field" %>
            </div>
            <div class="form-group">
                <%= f.submit t('Зареєструватися'), id: "register-button" %>
            </div>
            <div class="form-group">
                <%= link_to t('Вже маєте аккаунт?'), login_path, class: 'register-button' %>
            </div>
        <% end %>
    </div>
</body>
</html>